# Numpy(넘파이)

- `Numerical Python`의 약자
- 과학 연산을 위한 파이썬 핵심 라이브러리
- 대규모 다차원 배열 연산
- C/C ++ 및 포트란 코드 통합 도구 
- 기본적으로 모든 원소가 같은 자료형
> python은 느리지 않다!

- list vs. array

In [6]:
temp = [1,'가']
sum(temp)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

> 리스트는 여러가지 자료형을 넣을 수 있기 때문에
연산을 할 때 하나씩 컴퓨터가 type을 확인을 한다.  
그러나 배열은 동일한 자료만 있기 때문에 컴퓨터가 하나씩 자료형을 확인하지 않고 바로 연산이 가능하다.  
버스 탈 때 현금 vs. 카드

# 넘파이 가져오기

In [10]:
import numpy as np
np.__version__

'1.16.3'

- 속도비교

In [1]:
#참고만
list_square = range(1000)
%timeit [i**2 for i in list_square]

345 µs ± 13.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
#참고만
array_square = np.arange(1000)
%timeit array_square**2

1.75 µs ± 74.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# 넘파이 배열 만들기
- `np.array([],[],...)`
> 안에 대괄호는 리스트 X

- 1차원 배열 만들기
- vector라고도 부름

In [6]:
# arange 함수 이용
np.arange(1,4)

array([1, 2, 3])

In [8]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


- nddray 자료구조

In [9]:
type(arr1)

numpy.ndarray

> 넘파이가 제공하는 특수한 배열 자료구조 ndarray  
> `N-dimensional Array`의 약자

Q. `q_list = [1, 2, 3]` , `arr = np.array([1, 2, 3])` 에 있는 값을 두 배하라.

> 2를 곱해볼까?

In [10]:
q_list = [1, 2, 3]
q_list*2

[1, 2, 3, 1, 2, 3]

In [11]:
temp = []
for i in q_list:
    temp.append(i*2)
print(temp)

[2, 4, 6]


In [11]:
arr1 = np.array([1, 2, 3])

In [12]:
temp = []
for i in arr1:
    temp.append(i*2)
print(temp)

[2, 4, 6]


> ndarry에 더 간단하게 계산이 가능

- 벡터화 연산(vectorized operation)
> 각 원소에 대하여 반복 연산을 한 번에 처리

In [13]:
arr1 * 2

array([2, 4, 6])

> for문을 이용하는 것보다 계산속도 훨씬 빠르다

- map 복습

In [22]:
list(map(lambda x: x*2, arr1))

[2, 4, 6]

## 넘파이 연산

In [16]:
arr1 > 3

array([False, False, False])

In [17]:
arr1 == 6

array([False, False, False])

In [18]:
arr2 = np.array([4, 5, 6])
arr1 + arr2 

array([5, 7, 9])

In [19]:
arr3 = np.array([7,8,9,10])
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [30]:
arr1 * arr2 

array([ 4, 10, 18])

In [20]:
arr1 + 1

array([2, 3, 4])

> 넘파이 배열은 각 원소의 개수가 같아야함  
> 또는 하나의 값이면 가능

## N차원 배열 만들기

- 직사각형 형태를 따른다.

![](https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png)

## 2차원 배열 만들기
   - 가로 - 행(row)과 세로 - 열(column)
   - 행렬(matrix)로 불림

In [27]:
arr4 = np.array([[1, 2], [3, 4]])
arr4

array([[1, 2],
       [3, 4]])

In [81]:
# 크기(모양) 확인
arr4.shape

(2, 2)

In [28]:
# reshape함수 이용
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [82]:
# 행 확인
arr4.shape[0]

2

In [83]:
# 차원 확인
arr4.ndim

2

In [84]:
# 전치행렬(Transpose)
arr4.T

array([[1, 3],
       [2, 4]])

In [85]:
arr4.T.shape

(2, 2)

In [86]:
# 행의 개수
len(arr4)

2

In [87]:
# 열의 개수
len(arr4[0])

2

> 어차피 개수가 다 같으니깐 열의 개수는 인덱스에 상관없이 동일함

Q. arr5 = np.array([[7,8],[1,2]]) 와 arr4의 합과 곱을 구하라

In [91]:
arr5 = np.array([[7,8],[1,2]])
arr5

array([[7, 8],
       [1, 2]])

In [92]:
arr5.shape

(2, 2)

In [93]:
arr4

array([[1, 2],
       [3, 4]])

In [94]:
arr4.shape

(2, 2)

In [96]:
arr4 * arr5

array([[ 7, 16],
       [ 3,  8]])

> ?? 행렬의 곱이 왜 저런가 ?? ndarray만의 특성  
우리가 아는 행렬의 곱은 dot이란 함수를 사용

In [97]:
#우리가 아는 행렬의 곱
np.dot(arr4, arr5) #첫번째 열의 개수와 두번째 행의 개수가 같아야 계산됨

array([[ 9, 12],
       [25, 32]])

In [27]:
temp2 = np.array(np.arange(1,4)).reshape(3)

In [28]:
temp2

array([1, 2, 3])

In [33]:
np.dot(arr4,  temp2)

array([14, 32, 50])

## 3차원 배열 만들기
   - Tensor(텐서)라 불림

Q. 1~16을 3차원으로 2행 4열로 만들어라.

In [30]:
arr6 = np.array([[[1,2,3,4],
               [5,6,7,8]],
              [[9,10,11,12],
               [13,14,15,16]]])
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [31]:
np.array(np.arange(1,17)).reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

Q. arr6의 행,열,면,차원의 개수는?

In [32]:
len(arr6[0])

2

In [33]:
len(arr6[0][0])

4

In [34]:
arr6.ndim

3

In [35]:
arr6.shape
#(면, 행, 열)

(2, 2, 4)

## 배열 인덱싱

In [36]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [37]:
arr6[0] #1면

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr6[0][0] #(1면 1행)

array([1, 2, 3, 4])

In [39]:
arr6[0,0]

array([1, 2, 3, 4])

In [40]:
arr6[0][0][0] #1면 1행 1열

1

In [41]:
arr6[0,0,0]

1

In [42]:
arr6[-1][-1] #마지막 면의 마지막 행

array([13, 14, 15, 16])

## 배열 슬라이싱


In [43]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [44]:
arr6[1:] #2면이상 조회

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [45]:
arr6[:] # :은 전체를 뜻함

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [46]:
arr6[:,0,0] #각면의 1행과 1열

array([1, 9])

In [47]:
arr6[:, 0, 1:] #각면의 1번째 행과 (2번째 포함) 2번째 이후 열

array([[ 2,  3,  4],
       [10, 11, 12]])

In [48]:
arr6[:1, :1] #1면 2번째 행 이전의 행

array([[[1, 2, 3, 4]]])

#### 팬시 인덱싱(fancy indexing)
- 배열을 인덱싱에 사용
> `arr[[1]]` 과 `arr[1]`은 다른 것임, 헷갈리지 마세요~  
전자는 팬시 인덱싱이고 후자는 일반 인덱싱

- 배열안에 불리언으로 인덱싱할 경우 요소의 개수가 같아야함


In [49]:
arr6 > 10 #10이상의 값 조회

array([[[False, False, False, False],
        [False, False, False, False]],

       [[False, False,  True,  True],
        [ True,  True,  True,  True]]])

In [50]:
arr6[arr6 > 10]

array([11, 12, 13, 14, 15, 16])

In [51]:
arr6[arr6 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [52]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [53]:
arr6[np.array([True,False])] 

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [54]:
arr6[[True]] 

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1

In [55]:
arr6.shape[0]

2

불리언의 경우 인덱싱 요소 개수와 면의 크기가 같아야함  
2개는 무조건 나와야 함

In [56]:
arr6[[True,False]] #1면 True 2면 False

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [57]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [58]:
arr6[[True,False], [True,True]] #앞의 [true, false] 1면 True 2면 false -> 1행 True 2행 False

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

순서로 인덱싱 됨  
1단계 True, False로 [1,2,3,4],[5,6,7,8]이 필터 되고  
2단계 True, True로 두 배열 전부 불러오는 것임  

Q. 1,3를 출력하는 인덱싱은?

In [59]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [60]:
arr6[[True,False], [True,False] ,[True,False,True,False]]

array([1, 3])

- 인덱스로 접근

In [61]:
arr6[0][0][0] # 기본 인덱스로 접근 #팬시 인덱싱아니다ㅡ

1

In [62]:
arr6[[0],[0],[0]]

array([1])

In [63]:
arr6[[0],[0],[0,2]]

array([1, 3])

얘는 조합으로 인덱싱 됨   
1단계 0 0 0 0면 0행 0열  
2단계 0 0 2 0면 0행 2열

# 둘이 작동방법이 다름!

---

In [64]:
arr6[[0],[0],[0:]]

SyntaxError: invalid syntax (<ipython-input-64-0bf99ffa1b0c>, line 1)

> 배열안에서 범위로 인덱싱 불가능

In [65]:
arr6[[0],[0],:]

array([[1, 2, 3, 4]])

> l. 범위 인덱싱 하면 된다.

In [66]:
arr6[[1,0],[0],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

Q. arr6을 아래처럼 인덱싱 해보아라
```python
array([[11, 12],
       [ 7,  8],
       [15, 16]])
```

In [67]:
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

- 생각의 흐름  
마지막 2개를 가져와야 하니 범위 인덱싱을 쓰자   
`arr6[2:]`  
11,12는 2차원의 첫번째 행 해당 `arr6[[1],[0],2:]`  
7, 8은 1차원의 두번째 행 해당  
15, 16은 2차원의 두번째 행 해당

In [68]:
arr6[[1,0,1],[0,1,1],2:]

array([[11, 12],
       [ 7,  8],
       [15, 16]])